export const FS_REQUEST_SUCCEEDED = "FS_REQUEST_SUCCEEDED"
export const FS_REQUEST_FAILED = "FS_REQUEST_FAILED"

export const CREATE_WRITE_STREAM = "CREATE_WRITE_STREAM" 
export const CREATE_READ_STREAM = "CREATE_READ_STREAM"